import { ArrowRight, CheckCircle, Sparkles, FileText, Brain, Target, TrendingUp, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Link } from "react-router-dom";
import heroBanner from "@/assets/hero-banner.jpg";

export default function Landing() {
  const features = [
    {
      icon: Brain,
      title: "AI-Powered RFP Analysis",
      description: "Automatically extract key insights, requirements, and challenges from any RFP document.",
    },
    {
      icon: Target,
      title: "Smart Discovery Questions",
      description: "Generate tailored questionnaires to understand client needs and pain points.",
    },
    {
      icon: FileText,
      title: "Dynamic Proposal Builder",
      description: "Create winning proposals with AI-suggested content and case studies.",
    },
    {
      icon: TrendingUp,
      title: "Value Proposition Generation",
      description: "Craft compelling value propositions aligned with client business objectives.",
    },
  ];

  const testimonials = [
    {
      quote: "NovaIntel reduced our proposal creation time by 70%. The AI insights are incredibly accurate.",
      author: "Sarah Chen",
      role: "VP of Sales, TechCorp",
    },
    {
      quote: "The discovery questions generated by NovaIntel helped us win deals we thought were lost.",
      author: "Michael Rodriguez",
      role: "Presales Director, CloudSolutions",
    },
  ];

  return (
    <div className="min-h-screen bg-gradient-hero">
      {/* Navigation */}
      <nav className="sticky top-0 z-50 border-b border-border/40 bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
        <div className="mx-auto flex h-16 max-w-[1388px] items-center justify-between px-6">
          <div className="flex items-center gap-2">
            <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-gradient-primary">
              <span className="text-lg font-bold text-primary-foreground">N</span>
            </div>
            <span className="font-heading text-xl font-bold">
              Nova<span className="text-primary">Intel</span>
            </span>
          </div>
          <div className="flex items-center gap-4">
            <Link to="/login">
              <Button variant="ghost">Login</Button>
            </Link>
            <Link to="/register">
              <Button className="bg-gradient-primary">Get Started</Button>
            </Link>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="relative overflow-hidden py-20">
        <div className="mx-auto max-w-[1388px] px-6">
          <div className="grid gap-12 lg:grid-cols-2 lg:gap-16">
            <div className="flex flex-col justify-center space-y-8 animate-fade-in">
              <div className="inline-flex items-center gap-2 self-start rounded-full border border-primary/20 bg-primary/10 px-4 py-1.5 text-sm font-medium text-primary">
                <Sparkles className="h-4 w-4" />
                AI-Powered Presales Intelligence
              </div>
              <h1 className="font-heading text-5xl font-bold leading-tight tracking-tight lg:text-6xl">
                Accelerate Your Presales Process with{" "}
                <span className="bg-gradient-primary bg-clip-text text-transparent">AI</span>
              </h1>
              <p className="text-lg text-muted-foreground">
                NovaIntel automates RFP analysis, discovery questions, insights generation, case study mapping, and
                proposal creation—saving you time and winning more deals.
              </p>
              <div className="flex flex-wrap gap-4">
                <Link to="/register">
                  <Button size="lg" className="bg-gradient-primary shadow-lg hover:shadow-xl">
                    Get Started <ArrowRight className="ml-2 h-4 w-4" />
                  </Button>
                </Link>
                <Button size="lg" variant="outline">
                  Watch Demo
                </Button>
              </div>
            </div>
            <div className="relative animate-slide-up">
              <div className="overflow-hidden rounded-2xl shadow-glass">
                <img src={heroBanner} alt="NovaIntel Dashboard" className="h-full w-full object-cover" />
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20">
        <div className="mx-auto max-w-[1388px] px-6">
          <div className="mb-12 text-center">
            <h2 className="mb-4 font-heading text-4xl font-bold">Core Features</h2>
            <p className="text-lg text-muted-foreground">
              Everything you need to streamline presales from RFP to proposal
            </p>
          </div>
          <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-4">
            {features.map((feature, index) => (
              <Card
                key={index}
                className="group relative overflow-hidden border-border/40 bg-gradient-card backdrop-blur-sm transition-all hover:-translate-y-1 hover:shadow-glass"
              >
                <div className="p-6">
                  <div className="mb-4 inline-flex h-12 w-12 items-center justify-center rounded-xl bg-primary/10 text-primary transition-colors group-hover:bg-primary group-hover:text-primary-foreground">
                    <feature.icon className="h-6 w-6" />
                  </div>
                  <h3 className="mb-2 font-heading text-xl font-semibold">{feature.title}</h3>
                  <p className="text-sm text-muted-foreground">{feature.description}</p>
                </div>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonials Section */}
      <section className="py-20">
        <div className="mx-auto max-w-[1388px] px-6">
          <div className="mb-12 text-center">
            <h2 className="mb-4 font-heading text-4xl font-bold">Trusted by Presales Teams</h2>
            <p className="text-lg text-muted-foreground">See what our customers say about NovaIntel</p>
          </div>
          <div className="grid gap-8 md:grid-cols-2">
            {testimonials.map((testimonial, index) => (
              <Card
                key={index}
                className="border-border/40 bg-gradient-card p-8 backdrop-blur-sm transition-all hover:shadow-glass"
              >
                <div className="mb-6 flex items-center gap-1 text-accent">
                  {[...Array(5)].map((_, i) => (
                    <CheckCircle key={i} className="h-5 w-5 fill-current" />
                  ))}
                </div>
                <blockquote className="mb-6 text-lg font-medium">&ldquo;{testimonial.quote}&rdquo;</blockquote>
                <div>
                  <div className="font-semibold">{testimonial.author}</div>
                  <div className="text-sm text-muted-foreground">{testimonial.role}</div>
                </div>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20">
        <div className="mx-auto max-w-[1388px] px-6">
          <Card className="overflow-hidden border-border/40 bg-gradient-primary p-12 text-center text-primary-foreground shadow-glass">
            <h2 className="mb-4 font-heading text-4xl font-bold">Ready to Transform Your Presales?</h2>
            <p className="mb-8 text-lg opacity-90">
              Join hundreds of teams already using NovaIntel to win more deals faster
            </p>
            <Link to="/register">
              <Button size="lg" variant="secondary" className="shadow-lg">
                Start Free Trial <ArrowRight className="ml-2 h-4 w-4" />
              </Button>
            </Link>
          </Card>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-border/40 py-8 text-center text-sm text-muted-foreground">
        © 2025 NovaIntel. All rights reserved.
      </footer>
    </div>
  );
}
